"""updated demographic for blackjacack

Revision ID: 316c6722090e
Revises: acef960bd5fe
Create Date: 2024-07-02 10:10:26.795034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316c6722090e'
down_revision = 'acef960bd5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blackjack_experience', sa.String(length=32), nullable=False))
        batch_op.drop_column('skin_experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_experience', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_column('blackjack_experience')

    # ### end Alembic commands ###
