"""added participant id to demographic

Revision ID: 3cbc21da926f
Revises: 96754693ef49
Create Date: 2024-08-08 16:57:20.687542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbc21da926f'
down_revision = '96754693ef49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographic', schema=None) as batch_op:
        batch_op.drop_column('participant_id')

    # ### end Alembic commands ###
