"""increase model name length

Revision ID: 5b8a05800076
Revises: 182ae1761613
Create Date: 2024-08-12 11:38:41.275410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8a05800076'
down_revision = '182ae1761613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.alter_column('model_name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("'blackjack_CtoY_onnx_standard'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.alter_column('model_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'blackjack_CtoY_onnx_standard'"))

    # ### end Alembic commands ###
