"""removed server default

Revision ID: 8752fc8b9e04
Revises: de171e292349
Create Date: 2024-08-20 16:49:29.738023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8752fc8b9e04'
down_revision = 'de171e292349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.alter_column('system_frequency', existing_type=sa.Integer(), existing_nullable=False)
        batch_op.alter_column('unnecessarily_complex', existing_type=sa.Integer(), existing_nullable=False)
        batch_op.alter_column('easy_to_use', existing_type=sa.Integer(), existing_nullable=False)
        batch_op.alter_column('sus_need_support', existing_type=sa.Integer(), existing_nullable=False)
        batch_op.alter_column('well_integrated', existing_type=sa.Integer(), existing_nullable=False)
        batch_op.alter_column('inconsistency', existing_type=sa.Integer(), existing_nullable=False)
        batch_op.alter_column('learn_quickly', existing_type=sa.Integer(), existing_nullable=False)
        batch_op.alter_column('cumbersome', existing_type=sa.Integer(), existing_nullable=False)
        batch_op.alter_column('system_confident', existing_type=sa.Integer(), existing_nullable=False)
        batch_op.alter_column('pre_learning', existing_type=sa.Integer(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.alter_column('system_frequency', existing_type=sa.Integer(), server_default=sa.text("'0'"), existing_nullable=False)
        batch_op.alter_column('unnecessarily_complex', existing_type=sa.Integer(), server_default=sa.text("'0'"), existing_nullable=False)
        batch_op.alter_column('easy_to_use', existing_type=sa.Integer(), server_default=sa.text("'0'"), existing_nullable=False)
        batch_op.alter_column('sus_need_support', existing_type=sa.Integer(), server_default=sa.text("'0'"), existing_nullable=False)
        batch_op.alter_column('well_integrated', existing_type=sa.Integer(), server_default=sa.text("'0'"), existing_nullable=False)
        batch_op.alter_column('inconsistency', existing_type=sa.Integer(), server_default=sa.text("'0'"), existing_nullable=False)
        batch_op.alter_column('learn_quickly', existing_type=sa.Integer(), server_default=sa.text("'0'"), existing_nullable=False)
        batch_op.alter_column('cumbersome', existing_type=sa.Integer(), server_default=sa.text("'0'"), existing_nullable=False)
        batch_op.alter_column('system_confident', existing_type=sa.Integer(), server_default=sa.text("'0'"), existing_nullable=False)
        batch_op.alter_column('pre_learning', existing_type=sa.Integer(), server_default=sa.text("'0'"), existing_nullable=False)

    # ### end Alembic commands ###
