"""added ai_enabled to games

Revision ID: 96754693ef49
Revises: 514780676686
Create Date: 2024-07-17 16:34:43.798736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96754693ef49'
down_revision = '514780676686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('ai_enabled')

    # ### end Alembic commands ###
