"""added sus to survey

Revision ID: de171e292349
Revises: b148c8bb89ae
Create Date: 2024-08-20 16:46:16.090648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de171e292349'
down_revision = 'b148c8bb89ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_frequency', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('unnecessarily_complex', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('easy_to_use', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('sus_need_support', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('well_integrated', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('inconsistency', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('learn_quickly', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('cumbersome', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('system_confident', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('pre_learning', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_column('pre_learning')
        batch_op.drop_column('system_confident')
        batch_op.drop_column('cumbersome')
        batch_op.drop_column('learn_quickly')
        batch_op.drop_column('inconsistency')
        batch_op.drop_column('well_integrated')
        batch_op.drop_column('sus_need_support')
        batch_op.drop_column('easy_to_use')
        batch_op.drop_column('unnecessarily_complex')
        batch_op.drop_column('system_frequency')

    # ### end Alembic commands ###
